services:
  # PostgreSQL database with pgvector extension
  codeweaver-db:
    image: pgvector/pgvector:pg15
    container_name: codeweaver-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '9001:5432'
    volumes:
      - codeweaver-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis cache and message broker
  codeweaver-redis:
    image: redis:7-alpine
    container_name: codeweaver-redis
    restart: always
    ports:
      - '9002:6379'
    volumes:
      - codeweaver-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  codeweaver-db-data:
  codeweaver-redis-data: