packages:
  - apps/*
  - packages/*
  - tooling/*
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
  - esbuild
