import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import TRPCProvider from '@/utils/provider';

export const metadata: Metadata = {
  title: "CodeWeaver",
  description: "Generated by create-t3-app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TRPCProvider>{children}</TRPCProvider>
      </body>
    </html>
  );
}
